Merge rule_data.trusted_tasks into trusted_tasks
enterprise-contract/ec-policies pull request #1047
Opened 2024-06-21 14:00 UTC by simonbaird

Ernesto (reasonably IMO) assumed that this would work and I can't think of a good reason that it shouldn't, especially since it's such a small change.

It's true that we're moving towards the "trusted artifacts", aka "-oci-ta" tasks which mean we can permit custom tasks without requiring they they are trusted. But still, it's reasonable for teams to want to ensure their custom tasks are trusted, so I like the idea of make it more convenient.

2024-06-21 14:18 UTC, robnester-rh approved these changes
LGTM

2024-06-24 11:24 UTC, zregvart requested changes
We could do with docs on this, perhaps [here](https://enterprisecontract.dev/docs/ec-policies/release_policy.html#trusted_task__trusted). And we want to schema check the value as it is relatively complex

2024-06-24 15:09 UTC, simonbaird commented
I'll do some more work on this based on Zoran's suggestions.

2024-06-27 10:14 UTC, zregvart approved these changes

2024-06-27 10:15 UTC, zregvart approved these changes
We can also do the schema check and the docs in a followup...

2024-07-01 17:50 UTC, simonbaird commented
I did update the documentation a little, see the second commit.

Schema validation seems like a good idea, and we are doing similar elsewhere (`git grep json.match_schema`), but I think it could be done in a future PR rather than hold up this one.

I'll pull this out of draft.

2024-07-02 20:35 UTC, simonbaird commented
Let's merge.

2024-07-02 20:35 UTC, merged